version: "3.9"
name: "library"

services:
  nginx:
    image: nginx:latest
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - app
      - postgres
    networks:
      - nginx_network
    environment:
      UPLOAD_FILE_SIZE_LIMIT: 20

  app:
    build:
      context: ..
      dockerfile: .docker/Dockerfile
    container_name: library-api-prod
    hostname: library-api
    restart: always
    image: library-api
    # Uncomment this line in case you are in M1
    # platform: linux/amd64
    ports:
      - "3000:3000"
    networks:
      - "nginx_network"
    depends_on:
      - postgres

  postgres:
    container_name: postgres-container-prod
    image: postgres:latest
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: "user"
      POSTGRES_PASSWORD: "password"
      POSTGRES_DB: "library"
    volumes:
      - library-postgres:/var/lib/postgresql/data
    networks:
      - "nginx_network"

  pgadmin:
    container_name: pgadmin-container-prod
    image: dpage/pgadmin4
    hostname: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@email.com
      PGADMIN_DEFAULT_PASSWORD: admin
      SCRIPT_NAME: "/pgadmin4"
    ports:
      - 5050:80
    networks:
      - "nginx_network"

  migrate-deploy:
    build:
      context: ..
      dockerfile: .docker/Dockerfile
      target: migrate
    container_name: migrate-deploy-prod
    image: library-api-deploy
    # Uncomment this line in case you are in M1
    # platform: linux/amd64
    ports:
      - "3001:3001"
    networks:
      - "nginx_network"
    depends_on:
      - postgres

networks:
  nginx_network:
    external: true

volumes:
  library-postgres:
